on:
    push:
    pull_request:
        branches:
            - main
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            actions: read
            contents: write
        strategy:
            matrix:
                python-version: ["3.7", "3.8", "3.9", "3.10"]
        name: Python ${{ matrix.python-version }}
        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - uses: actions/setup-python@v5
              with:
                  python-version: ${{ matrix.python-version }} # Version range or exact version of a Python version to use, using SemVer's version range syntax
                  architecture: "x64" # optional x64 or x86. Defaults to x64 if not specified
            - name: install requirements
              run: pip install -r requirements.txt
            - uses: jakebailey/pyright-action@v1
